version: 0.2
run-as: root
env:
  git-credential-helper: yes
  parameter-store:
    build_ssh_key: "gdp-pear-private-key"

phases:
  install:
    commands:
      - mkdir -p ~/.ssh
      - echo "$build_ssh_key" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
      - git config --global url."git@github.com:".insteadOf "https://github.com/"
  build:
    commands:
      - bash ./.titan/scripts/code_analysis/terraform.sh
      # Run pre-commit checks
      - make check
