/**
* # S3 Curated Component
* This component creates an S3 bucket which will contain the curated files generated by voyager-app.
* ### Running via CircleCI
* For development purpose, you can run the component via CircleCI.
* You need to create a voyager_variables.yaml file and set the `INPUTS_FILE`
* environment variable with the path of that file.
*/
module "curated_datalake_bucket" {
  source = "git@github.com:JSainsburyPLC/voyager-terraform-modules.git//s3_datalake_bucket?ref=v1.1"

  enable_bucket       = true
  bucket_name         = "${var.environment}-curated-src-${var.project_name}"
  data_source         = var.project_name
  environment         = var.environment
  project             = var.project_name
  ticket_ref          = var.ticket_ref
  costcentre          = var.costcentre
  email               = var.email
  aws_account_id      = var.account_number
  rw_trusted_arns     = var.curated_read_write_trusted_arns
  ro_trusted_arns     = var.curated_read_only_trusted_arns
  enable_notification = var.enable_notification
  subrecv_arn_list    = var.curated_subrecv_arn_list
  event_notification  = var.curated_notification_events
}

